services:

  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: cadeaagua-app
    container_name: cadeaagua-app
    volumes:
      - .:/var/www
    networks:
      - cadeaagua 
    environment:
      - APP_ENV=local

  nginx:
    image: nginx:latest
    container_name: cadeaagua-nginx
    volumes:
      - .:/var/www
      - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - cadeaagua 

  mysql:
    image: mysql:8
    container_name: cadeaagua-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadeaagua 
      MYSQL_USER: cadeaagua 
      MYSQL_PASSWORD: cadeaagua 
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - cadeaagua 

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: cadeaagua-pma
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - cadeaagua 


networks:
  cadeaagua:
    name: cadeaagua

volumes:
  mysql_data:
