services:

  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: cadeaagua-app
    container_name: cadeaagua-app
    volumes:
     - public:/var/www/public
     - storage:/var/www/storage
    networks:
      - cadeaagua

  nginx:
    image: nginx:stable-alpine
    container_name: cadeaagua-nginx
    restart: unless-stopped
    volumes:
      - public:/var/www/public:ro
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - cadeaagua

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot

  postgres:
    image: postgis/postgis:15-3.4
    container_name: cadeaagua-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cadeaagua_data:/var/lib/postgresql/data
    networks:
      - cadeaagua

networks:
  cadeaagua:
    name: cadeaagua

volumes:
  cadeaagua_data:
  public:
  letsencrypt:
  certbot:
  storage:
