services:

  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: novoendereco-app_r
    container_name: novoendereco-app_r
    volumes:
      - .:/var/www
    networks:
      - novoendereco_r
    environment:
      - APP_ENV=local

  nginx:
    image: nginx:latest
    container_name: novoendereco-nginx_r
    volumes:
      - .:/var/www
      - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - novoendereco_r

  mysql:
    image: mysql:8
    container_name: novoendereco-mysql_r
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: novoendereco
      MYSQL_USER: novoendereco
      MYSQL_PASSWORD: novoendereco
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - novoendereco_r

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: novoendereco-pma_r
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - novoendereco_r


networks:
  novoendereco_r:

volumes:
  mysql_data:
