services:

  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: cadeaagua-app
    container_name: cadeaagua-app
    volumes:
      - .:/var/www
    networks:
      - cadeaagua 
    environment:
      - APP_ENV=local

  nginx:
    image: nginx:latest
    container_name: cadeaagua-nginx
    volumes:
      - .:/var/www
      - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - cadeaagua 

  postgres:
    image: postgis/postgis:15-3.4
    container_name: cadeaagua-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cadeaagua

networks:
  cadeaagua:
    name: cadeaagua

volumes:
  postgres_data:
